package com.github.ilms49898723.minttranslator.errorhandling;

public enum ErrorCode {
    INVALID_UCF_FILE,
    INVALID_IDENTIFIER,
    INVALID_OPERATOR,
    UNDEFINED_MODULE,
    UNDEFINED_SYMBOL,
    PORT_NAME_NOT_MATCH,
    LAYER_ERROR_FLOW,
    LAYER_ERROR_CONTROL,
    ASSIGN_PORTS_NOT_MATCH,
    NO_VALID_PORTS,
    NOT_BINARY_UNARY_OPERATOR,
    OPERATOR_INPUTS_NOT_MATCH,
    CONTROL_OPERATOR_NOT_SUPPORT
}
